title: SysInflam HuDB Dataset Release and Updates
name: Developed and maintained by Laboratory of Translational Systems Immunology - Sidra Medicine
description: <a href="http://sepsis.gxbsidra.org/dm3/landing.gsp">SysInflam HuDB Landing Page</a>
theme: jekyll-theme-cayman
github:
  is_project_page: false
